import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const directory = path.dirname(fileURLToPath(import.meta.url));

const state = {
  asOf: "2026-07-27T02:40:46.713Z",
  cash: 62241,
  debt: 275000,
  buildingValue: 251850,
  freeSlots: 3,
  minimumCash: 5000,
  prospectorProgress: 0,
  prospectorTarget: 10,
  currentlyClaimableRewards: 0,
};

const quarry = {
  level: 1,
  approximateInitialMaterialsValue: 26452,
  buildHours: 3,
  materialReturnRate: 1,
  materials: {
    reinforcedConcrete: 28,
    bricks: 385,
    planks: 112,
    constructionUnits: 7,
  },
};

const rewards = [
  { scraps: 10, reward: 5000 },
  { scraps: 50, reward: 25000 },
  { scraps: 100, reward: 50000 },
  { scraps: 200, reward: 100000 },
  { scraps: 500, reward: 100000 },
  { scraps: 1000, reward: 100000 },
  { scraps: 2000, reward: 100000 },
];

let cumulativeReward = 0;
let previousScraps = 0;
const tiers = rewards.map(({ scraps, reward }) => {
  cumulativeReward += reward;
  const incrementalScraps = scraps - previousScraps;
  previousScraps = scraps;
  return {
    target_label: `${scraps} 次`,
    target_scraps: scraps,
    tier_reward: reward,
    cumulative_reward: cumulativeReward,
    incremental_scraps: incrementalScraps,
    marginal_reward_per_scrap: reward / incrementalScraps,
    one_slot_hours: Math.ceil(scraps / 1) * quarry.buildHours,
    two_slot_hours: Math.ceil(scraps / 2) * quarry.buildHours,
    three_slot_hours: Math.ceil(scraps / 3) * quarry.buildHours,
    one_slot_average_reward_per_hour: cumulativeReward / (Math.ceil(scraps / 1) * quarry.buildHours),
  };
});

const debtBuildingFloor = state.debt * 0.8;
const buildingValueHeadroom = state.buildingValue - debtBuildingFloor;
const oneSlotCashAfterInitialMaterials = state.cash - quarry.approximateInitialMaterialsValue;
const twoSlotCashAfterInitialMaterials = state.cash - 2 * quarry.approximateInitialMaterialsValue;
const threeSlotCashAfterInitialMaterials = state.cash - 3 * quarry.approximateInitialMaterialsValue;

const result = {
  generatedAtUtc: new Date().toISOString(),
  state,
  quarry,
  debtBuildingFloor,
  buildingValueHeadroom,
  oneSlotCashAfterInitialMaterials,
  twoSlotCashAfterInitialMaterials,
  threeSlotCashAfterInitialMaterials,
  tiers,
  recommendation: {
    action: "Run one test cycle, verify the counter moves from 0/10 to 1/10, then use one spare slot until the 10-scrap tier is complete.",
    reason: "One slot avoids delaying the two remaining expansion slots; the same returned Q0 materials can fund each subsequent L1 Quarry rebuild.",
    stretchTarget: 200,
    stopReason: "Marginal rewards fall sharply after the 200-scrap tier and the slot becomes more valuable for the Tools pivot.",
  },
};

fs.writeFileSync(path.join(directory, "prospector-results.json"), `${JSON.stringify(result, null, 2)}\n`);

const sources = [
  {
    id: "prospector_live",
    label: "Authenticated achievement overview and normalized company state",
    path: "chrome-automation/sim/autopilot/analysis/prospector-loop-2026-07-26/prospector-results.json",
  },
  {
    id: "game_facts",
    label: "Measured Quarry materials and build time",
    path: "chrome-automation/sim/shared/facts/game-facts.json",
  },
  {
    id: "official_construction",
    label: "Official construction and scrapping guide",
    href: "https://www.simcompanies.com/pages/construction-guide/",
  },
  {
    id: "official_achievements",
    label: "Official realm achievement rewards",
    href: "https://www.simcompanies.com/pages/realms-guide/",
  },
  {
    id: "official_bonds",
    label: "Official bond-related scrapping restriction",
    href: "https://www.simcompanies.com/pages/bonds-guide/",
  },
  {
    id: "public_company",
    label: "Current public company building value and debt",
    href: "https://www.simcompanies.com/api/v3/companies/5714348/",
  },
];

const tableSource = {
  query: {
    engine: "embedded",
    sql: "SELECT target_scraps, tier_reward, cumulative_reward, incremental_scraps, marginal_reward_per_scrap, one_slot_hours, two_slot_hours, three_slot_hours FROM prospector_tiers",
    description: "Projection over the embedded tier model generated by build-report.mjs; calculations execute in JavaScript.",
    executed_at: result.generatedAtUtc,
  },
};

const artifact = {
  surface: "report",
  manifest: {
    version: 1,
    surface: "report",
    title: "Prospector Loop Economics",
    description: "A current-state assessment of repeatedly building and scrapping L1 Quarries for Prospector achievement rewards.",
    generatedAt: result.generatedAtUtc,
    cards: [],
    charts: [
      {
        id: "prospector_efficiency_chart",
        title: "Prospector 累计平均奖励效率",
        subtitle: "一个建筑槽连续循环 L1 Quarry；奖励效率在 200 次达到峰值，之后下降。",
        type: "bar",
        intent: "comparison",
        question: "使用一个空闲建筑槽时，各累计拆除目标的平均奖励效率是多少？",
        rationale: "七个离散成就档位适合用柱状图比较单位时间累计奖励，且零基线能够诚实展示回报差距。",
        dataset: "prospector_tiers",
        source: {
          query: {
            engine: "embedded",
            sql: "SELECT target_label, target_scraps, cumulative_reward, one_slot_hours, one_slot_average_reward_per_hour FROM prospector_tiers",
            description: "Projection over the embedded tier model generated by build-report.mjs; calculations execute in JavaScript.",
            executed_at: result.generatedAtUtc,
          },
        },
        valueFormat: "currency",
        unit: "$/小时",
        encodings: {
          x: { field: "target_label", type: "nominal", label: "累计拆除目标" },
          y: { field: "one_slot_average_reward_per_hour", type: "quantitative", label: "平均奖励效率", unit: "$/小时" },
          tooltip: [
            { field: "cumulative_reward", type: "quantitative", label: "累计奖励", format: "currency" },
            { field: "one_slot_hours", type: "quantitative", label: "累计时间", unit: "小时" },
          ],
        },
        xAxisTitle: "累计拆除目标",
        yAxisTitle: "平均奖励（$/小时）",
        labels: { values: "all" },
        palette: { kind: "sequential", name: "blue" },
        settings: { showValues: true, sort: "none", yMin: 0 },
        layout: "full",
      },
    ],
    tables: [
      {
        id: "prospector_tiers_table",
        title: "Prospector 奖励阶梯",
        subtitle: "时间假设每座 L1 Quarry 建造 3 小时；拆除后立即用返还建材重建。",
        dataset: "prospector_tiers",
        source: tableSource,
        defaultSort: { field: "target_scraps", direction: "asc" },
        density: "spacious",
        layout: "full",
        columns: [
          { field: "target_scraps", label: "累计拆除", format: "number" },
          { field: "tier_reward", label: "本档奖励", format: "currency" },
          { field: "cumulative_reward", label: "累计奖励", format: "currency" },
          { field: "marginal_reward_per_scrap", label: "本档每次拆除奖励", format: "currency" },
          { field: "one_slot_hours", label: "1 个槽位", format: "number", unit: "小时" },
          { field: "two_slot_hours", label: "2 个槽位", format: "number", unit: "小时" },
          { field: "three_slot_hours", label: "3 个槽位", format: "number", unit: "小时" },
        ],
      },
    ],
    sources,
    blocks: [
      { id: "title", type: "markdown", body: "# Prospector Loop Economics" },
      {
        id: "executive_summary",
        type: "markdown",
        body: "## Executive Summary\n\n- **这基本属于低成本成就循环，但不是立即免费的现金。** L1 Quarry 拆除会返还全部建材，同一批建材可以反复使用；主要成本是第一次占用约 $26.5k 建材和每轮 3 小时。\n- **先做一次现场验证。** 当前实时进度为 0/10；第一次应只建一座并拆除，确认计数变为 1/10 后再循环，避免把规则文字误当成已实测行为。\n- **推荐先做到 10 次，再根据 Tools 进度延长到 200 次。** 一个空槽完成首档需约 30 小时并奖励 $5k；到 200 次累计约 25 天、奖励 $180k，之后边际回报明显下降。",
      },
      {
        id: "mechanics",
        type: "markdown",
        body: `## 建材可以循环，真正消耗的是时间和槽位\n\n官方规则说明 L1、L2 建筑拆除会返还全部投入建材。当前测得 L1 Quarry 需要 28 Reinforced Concrete、385 Bricks、112 Planks 和 7 Construction Units，价值约 $${quarry.approximateInitialMaterialsValue.toLocaleString("en-US")}，建造时间 ${quarry.buildHours} 小时。\n\n因此完成一次循环后，返还的 Q0 建材可以直接建下一座 Quarry。它不是把 $26.5k 每次烧掉，而是反复占用同一批建材。`,
      },
      {
        id: "current_constraints",
        type: "markdown",
        body: `## 当前债务不会阻止第一轮，但三槽并行现金不足\n\n当前公开公司数据为建筑价值 $${state.buildingValue.toLocaleString("en-US")}、债务 $${state.debt.toLocaleString("en-US")}。债务规则要求拆除后建筑价值不得低于债务的 80%，即 $${debtBuildingFloor.toLocaleString("en-US")}；当前仍有 $${buildingValueHeadroom.toLocaleString("en-US")} 余量，所以拆掉临时 L1 Quarry 后不会触发该限制。\n\n现金 $${state.cash.toLocaleString("en-US")} 足够买一套或两套建材：两套后约剩 $${twoSlotCashAfterInitialMaterials.toLocaleString("en-US")}，仍高于 $${state.minimumCash.toLocaleString("en-US")} 现金底线；三套需要约 $${(3 * quarry.approximateInitialMaterialsValue).toLocaleString("en-US")}，目前不足。`,
      },
      {
        id: "tier_interpretation",
        type: "markdown",
        body: "## 前 200 次值得利用，之后开始明显变慢\n\n首档 10 次只是小奖励，但可以验证循环。50、100、200 次档位的边际奖励更高；使用一个原本空闲的建筑槽，做到 200 次累计约 600 小时、获得 $180k。500 次以后每次拆除对应的奖励迅速下降，而且会持续占用未来 Tools 扩张所需槽位。",
      },
      { id: "efficiency_chart_block", type: "chart", chartId: "prospector_efficiency_chart", layout: "full" },
      { id: "tiers_table_block", type: "table", tableId: "prospector_tiers_table", layout: "full" },
      {
        id: "recommendations",
        type: "markdown",
        body: "## 推荐执行顺序\n\n1. 只建一座 L1 Quarry，3 小时完成后拆除。\n2. 立即读取成就页，确认 0/10 变为 1/10。\n3. 验证成功后，用同一批返还建材循环到 10/10。\n4. 保留另外两个空槽给 Farm、Tools 或其他高回报建设。\n5. 如果 Tools 建设尚未需要该槽位，可继续循环到 200 次；需要槽位时随时停止。",
      },
      {
        id: "further_questions",
        type: "markdown",
        body: "## Further Questions\n\n- 第一次拆除后，成就计数是否实时变为 1/10？\n- 实际建造页面的当前市场采购总价是否仍接近 $26.5k？\n- 在 Tools 第一批建筑开工时，Prospector 应在哪一档暂停以释放槽位？",
      },
      {
        id: "caveats",
        type: "markdown",
        body: "## Caveats and Assumptions\n\n- 全额返还指返还 Q0 建筑材料，不是直接返还现金；材料市价波动可能造成账面价值变化。\n- 重复建造同一类型应按每次 scrap 事件计数，但尚未在这个账号上实际完成第一轮，因此执行前必须用 0→1 验证。\n- 计算不包含操作延迟、闹钟误差、未来建筑槽机会成本或材料订单深度。\n- 当前没有待领取成就奖励；此前仅凭门槛推算的“可能未领取奖励”已经被实时成就 API 排除。",
      },
    ],
  },
  snapshot: {
    version: 1,
    status: "ready",
    generatedAt: result.generatedAtUtc,
    datasets: { prospector_tiers: tiers },
    accessIssues: [],
  },
  sources,
};

fs.writeFileSync(path.join(directory, "artifact.json"), `${JSON.stringify(artifact, null, 2)}\n`);
console.log(JSON.stringify({ ok: true, result: path.join(directory, "prospector-results.json"), artifact: path.join(directory, "artifact.json") }));
